<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Harshgiris-MacBook-Pro.local" failures="1" tests="1" name="POM_Dynamic_Logout_Timeout" time="6.018" errors="0" timestamp="2019-12-27T17:24:59 NZDT">
  <testcase classname="com.herokuapp.theinternet.loginpagetests.NegativeLoginTests" name="negativeTest" time="1.061">
    <failure type="java.lang.AssertionError" message="expected [Hello World!] but found []">
      <![CDATA[java.lang.AssertionError: expected [Hello World!] but found []
at com.herokuapp.theinternet.loginpagetests.NegativeLoginTests.negativeTest(NegativeLoginTests.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- negativeTest -->
  <testcase classname="com.herokuapp.theinternet.loginpagetests.NegativeLoginTests" name="dynamic_Loading_Timeout" time="0.0">
    <ignored/>
  </testcase> <!-- dynamic_Loading_Timeout -->
  <testcase classname="com.herokuapp.theinternet.loginpagetests.NegativeLoginTests" name="stale_Element_Test_Exception" time="0.0">
    <ignored/>
  </testcase> <!-- stale_Element_Test_Exception -->
  <testcase classname="com.herokuapp.theinternet.loginpagetests.NegativeLoginTests" name="disabled_Element_Exception" time="0.0">
    <ignored/>
  </testcase> <!-- disabled_Element_Exception -->
</testsuite> <!-- POM_Dynamic_Logout_Timeout -->
